# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 14:29
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('log_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlog',
            name='data_user',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='registerlog',
            name='modifications',
            field=jsonfield.fields.JSONField(),
        ),
    ]
